name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata for Docker image
      id: metadata
      uses: docker/metadata-action@v4
      with:
        images: egron2/prakt2
        tags: |
          type=ref,event=branch
          type=ref,event=tag

    - name: Get short commit ID
      id: shortsha
      run: echo "::set-output name=sha::$(git rev-parse --short $GITHUB_SHA)"

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: egron2/prakt2:${{ steps.shortsha.outputs.sha }}
        labels: ${{ steps.metadata.outputs.labels }}
